"""FixedNamesOfTablePerson

Revision ID: 6c9ddf0b8afc
Revises: 5dcddcf9446d
Create Date: 2024-12-06 19:31:40.586515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9ddf0b8afc'
down_revision: Union[str, None] = '5dcddcf9446d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_id'), 'person', ['id'], unique=False)
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.drop_index('ix_People_id', table_name='People')
    op.drop_index('ix_People_name', table_name='People')
    op.drop_table('People')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    op.create_index('ix_People_name', 'People', ['name'], unique=False)
    op.create_index('ix_People_id', 'People', ['id'], unique=False)
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_index(op.f('ix_person_id'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
