"""Autoincremental ID

Revision ID: e08ae77157da
Revises: 6c9ddf0b8afc
Create Date: 2024-12-07 16:23:40.483611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08ae77157da'
down_revision: Union[str, None] = '6c9ddf0b8afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
